version: '3'

services:
  client:
    build:
      context: ./FrontEnd
    ports:
      - 8000:8000
    depends_on:
      - server

  server:
    build:
      context: ./BackEnd
    ports:
      - 3000:3000
